// Mock data for development when the API is unavailable
// This allows previewing the UI without a running backend

import type { App, Category } from './api/types'

export const mockCategories: Category[] = [
  { id: '1', name: 'Productivity', slug: 'productivity', iconUrl: null, description: 'Get more done', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: '2', name: 'Creative', slug: 'creative', iconUrl: null, description: 'Express yourself', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: '3', name: 'Developer Tools', slug: 'developer-tools', iconUrl: null, description: 'Build faster', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: '4', name: 'Education', slug: 'education', iconUrl: null, description: 'Learn anything', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: '5', name: 'Entertainment', slug: 'entertainment', iconUrl: null, description: 'Have fun', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
]

export const mockApps: App[] = [
  {
    id: '1',
    name: 'AI Writing Assistant',
    slug: 'ai-writing-assistant',
    tagline: 'Write better, faster with AI-powered suggestions',
    description: 'A powerful writing assistant that helps you craft compelling content with intelligent suggestions and real-time editing support.',
    iconUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=200&h=200&fit=crop',
    websiteUrl: 'https://example.com',
    pricingModel: 'FREEMIUM',
    status: 'APPROVED',
    featured: true,
    creatorId: '1',
    categoryId: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    downloadCount: 12500,
    viewCount: 45000,
    avgRating: 4.8,
  },
  {
    id: '2',
    name: 'Smart Code Review',
    slug: 'smart-code-review',
    tagline: 'AI-powered code analysis for better development',
    description: 'Automatically review your code for bugs, security issues, and best practices with machine learning.',
    iconUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=200&h=200&fit=crop',
    websiteUrl: 'https://example.com',
    pricingModel: 'FREE',
    status: 'APPROVED',
    featured: false,
    creatorId: '2',
    categoryId: '3',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    downloadCount: 8900,
    viewCount: 32000,
    avgRating: 4.6,
  },
  {
    id: '3',
    name: 'Creative Studio Pro',
    slug: 'creative-studio-pro',
    tagline: 'Generate stunning visuals with AI',
    description: 'Create beautiful images, illustrations, and designs using cutting-edge AI technology.',
    iconUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&h=200&fit=crop',
    websiteUrl: 'https://example.com',
    pricingModel: 'PAID',
    status: 'APPROVED',
    featured: true,
    creatorId: '3',
    categoryId: '2',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    downloadCount: 15200,
    viewCount: 58000,
    avgRating: 4.9,
  },
  {
    id: '4',
    name: 'Language Tutor AI',
    slug: 'language-tutor-ai',
    tagline: 'Learn any language with personalized AI lessons',
    description: 'Interactive language learning powered by AI that adapts to your skill level and learning style.',
    iconUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=200&h=200&fit=crop',
    websiteUrl: 'https://example.com',
    pricingModel: 'FREEMIUM',
    status: 'APPROVED',
    featured: false,
    creatorId: '4',
    categoryId: '4',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    downloadCount: 22000,
    viewCount: 78000,
    avgRating: 4.7,
  },
  {
    id: '5',
    name: 'Music Generator',
    slug: 'music-generator',
    tagline: 'Create original music tracks instantly',
    description: 'Generate royalty-free music for your projects with AI-powered composition.',
    iconUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=200&h=200&fit=crop',
    websiteUrl: 'https://example.com',
    pricingModel: 'PAID',
    status: 'APPROVED',
    featured: false,
    creatorId: '5',
    categoryId: '5',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    downloadCount: 6700,
    viewCount: 24000,
    avgRating: 4.5,
  },
  {
    id: '6',
    name: 'Data Insights Pro',
    slug: 'data-insights-pro',
    tagline: 'Turn data into actionable insights',
    description: 'Analyze complex datasets and generate visual reports with AI assistance.',
    iconUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=200&h=200&fit=crop',
    websiteUrl: 'https://example.com',
    pricingModel: 'FREEMIUM',
    status: 'APPROVED',
    featured: true,
    creatorId: '6',
    categoryId: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    downloadCount: 11300,
    viewCount: 41000,
    avgRating: 4.4,
  },
  {
    id: '7',
    name: 'API Builder',
    slug: 'api-builder',
    tagline: 'Generate REST APIs from natural language',
    description: 'Describe your API in plain English and let AI build it for you.',
    iconUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=200&h=200&fit=crop',
    websiteUrl: 'https://example.com',
    pricingModel: 'FREE',
    status: 'APPROVED',
    featured: false,
    creatorId: '7',
    categoryId: '3',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    downloadCount: 9400,
    viewCount: 35000,
    avgRating: 4.3,
  },
  {
    id: '8',
    name: 'Video Editor AI',
    slug: 'video-editor-ai',
    tagline: 'Edit videos with AI-powered tools',
    description: 'Professional video editing made easy with intelligent automation and effects.',
    iconUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=200&h=200&fit=crop',
    websiteUrl: 'https://example.com',
    pricingModel: 'PAID',
    status: 'APPROVED',
    featured: true,
    creatorId: '8',
    categoryId: '2',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    downloadCount: 18600,
    viewCount: 67000,
    avgRating: 4.8,
  },
  {
    id: '9',
    name: 'Study Buddy',
    slug: 'study-buddy',
    tagline: 'Your AI-powered study companion',
    description: 'Flashcards, quizzes, and personalized study plans generated by AI.',
    iconUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=200&h=200&fit=crop',
    websiteUrl: 'https://example.com',
    pricingModel: 'FREE',
    status: 'APPROVED',
    featured: false,
    creatorId: '9',
    categoryId: '4',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    downloadCount: 31000,
    viewCount: 95000,
    avgRating: 4.9,
  },
  {
    id: '10',
    name: 'Game Design Studio',
    slug: 'game-design-studio',
    tagline: 'Create games without coding',
    description: 'Design and publish games using AI-assisted tools and templates.',
    iconUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&h=200&fit=crop',
    websiteUrl: 'https://example.com',
    pricingModel: 'FREEMIUM',
    status: 'APPROVED',
    featured: false,
    creatorId: '10',
    categoryId: '5',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    downloadCount: 14200,
    viewCount: 52000,
    avgRating: 4.6,
  },
  {
    id: '11',
    name: 'Meeting Notes AI',
    slug: 'meeting-notes-ai',
    tagline: 'Never miss a detail from your meetings',
    description: 'Automatically transcribe and summarize meetings with AI.',
    iconUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=200&h=200&fit=crop',
    websiteUrl: 'https://example.com',
    pricingModel: 'FREEMIUM',
    status: 'APPROVED',
    featured: false,
    creatorId: '11',
    categoryId: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    downloadCount: 8100,
    viewCount: 29000,
    avgRating: 4.5,
  },
  {
    id: '12',
    name: 'Photo Enhancer',
    slug: 'photo-enhancer',
    tagline: 'Transform photos with one click',
    description: 'AI-powered photo enhancement, restoration, and editing.',
    iconUrl: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=200&h=200&fit=crop',
    websiteUrl: 'https://example.com',
    pricingModel: 'FREE',
    status: 'APPROVED',
    featured: false,
    creatorId: '12',
    categoryId: '2',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    downloadCount: 27500,
    viewCount: 89000,
    avgRating: 4.7,
  },
] as App[]
